import standardpostpiv as spp

report = spp.get_basic_2D2C_report('piv_test_data.hdf')
filenames = report.create(
    notebook_filename='piv_test_data_evaluation.ipynb',
    execute_notebook=True,
    overwrite=True,
    inplace=True,
    to_html=True,
)

# open HTML report in web browser:
import webbrowser

webbrowser.open_new(filenames['html'])

# from standardpostpiv.notebook import PIVReportNotebook
#
# report = PIVReportNotebook('piv_test_data.hdf')
#
# from standardpostpiv.notebook_utils.pivreport_sections import imports, statistics, pdfs, \
#     displacement, monitor, normality
#
# report.add_section(imports.section, level=2)
# report.add_section(statistics.section, level=2)
# report.add_section(pdfs.section, level=2)
# report.add_section(displacement.main_section, level=2)
# report.add_section(displacement.section_mean_displacement, level=3)
# report.add_section(displacement.section_instantaneous_velocity, level=3)
# report.add_section(monitor.points(), level=2)
# report.add_section(monitor.convergence(), level=3)
# report.add_section(monitor.line(None), level=3)
# # report.add_section(normality.section_normality_check, level=2)
#
# ntb = report.create(execute_notebook=True,
#                     overwrite=True,
#                     notebook_filename='test_autogenerated_nb.ipynb',
#                     inplace=True)
